Instrumentation run for lzma

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -225,8 +225,8 @@ jobs:
         if: ${{ matrix.installer && startsWith(matrix.os, 'windows') }}
         run: |
           cd installers
-          iscc installer.iss
-          mv Output/setupSasView.exe dist
+          for i in fast normal max ultra; do echo $i; sed -i s@^Compression=.*@Compression=lzma/$i@ installer.iss; time iscc installer.iss 2>&1 > output.log; stat -c%s Output/setupSasView.exe; mv Output/setupSasView.exe dist/setupSasView-$i.exe; echo; done
+          ls -l dist
 
       - name: Build sasview installer dmg file (OSX)
         if: ${{ matrix.installer && startsWith(matrix.os, 'macos') }}
@@ -307,210 +307,210 @@ jobs:
           keylocker-cert-sha1-hash: ${{ secrets.KEYLOCKER_CERT_SHA1_HASH }}
 
 
-      - name: Publish installer package
-        if: ${{ matrix.installer }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
-          path: |
-            installers/dist/setupSasView*.exe
-            installers/dist/SasView6-macos-13.dmg
-            installers/dist/SasView6-macos-latest.dmg
-            installers/dist/SasView*.tar.gz
-          if-no-files-found: ignore
-
-
-  test-installer:
-    needs: [ build-matrix ]
-
-    strategy:
-      matrix:
-        os: [ windows-latest, macos-latest, ubuntu-22.04 ]
-        python-version: [ 3.11 ]
-      fail-fast: false
-
-    name: Test installer
-
-    runs-on: ${{ matrix.os }}
-
-    steps:
-      - name: Set variables (Windows)
-        if: ${{ startsWith(matrix.os, 'windows') }}
-        run: |
-          echo "INSTALL_PATH=$PWD/sasview/" >> $GITHUB_ENV
-          echo "RUN_SASVIEW=$PWD/sasview/sasview.exe" >> $GITHUB_ENV
-
-      - name: Set variables (Linux)
-        if: ${{ startsWith(matrix.os, 'ubuntu') }}
-        run: |
-          echo "INSTALL_PATH=$PWD/sasview/" >> $GITHUB_ENV
-          echo "RUN_SASVIEW=$PWD/sasview/sasview" >> $GITHUB_ENV
-
-      - name: Set variables (Windows Powershell)
-        if: ${{ startsWith(matrix.os, 'windows') }}
-        shell: powershell
-        # unfortunately we end up tripping over ourselves with paths
-        # later on and need a PS version of the install path
-        run: |
-          "INSTALL_WIN_PATH=$(Get-Location)/sasview/" >> $env:GITHUB_ENV
-
-      ### Obtain the installer, either from the previous step
-      ### or from a previous run of the workflow
-
-      - name: Retrieve installer (workflow image)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' }}
-        uses: actions/download-artifact@v4
-        id: download
-        with:
-          name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
-
-      - name: Set variables for download (workflow image)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' }}
-        run: |
-          echo "DL_PATH=${{steps.download.outputs.download-path}}" >> $GITHUB_ENV
-
-      - name: Set variables for download (workflow image) (Windows)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' && startsWith(matrix.os, 'windows') }}
-        shell: powershell
-        run: |
-          "DL_WIN_PATH=${{steps.download.outputs.download-path}}" >> $env:GITHUB_ENV
-
-      - name: Retrieve installer (old image)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' }}
-        id: download-old-installer
-        uses: dawidd6/action-download-artifact@v6
-        with:
-          # Select a specific installer image based on the GitHub Actions run id
-          run_id: ${{ env.INSTALLER_OLD_RUNID }}
-          name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
-          path: downloads
-          if_no_artifact_found: fail
-
-      - name: Set variables for download (old image)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' }}
-        run: |
-          echo "DL_PATH=$PWD/downloads" >> $GITHUB_ENV
-
-      - name: Set variables for download (old image) (Windows)
-        if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' && startsWith(matrix.os, 'windows') }}
-        shell: powershell
-        run: |
-          "DL_WIN_PATH=$(Get-Location)/downloads" >> $env:GITHUB_ENV
-
-      - name: Check downloads
-        run: |
-          echo "Sasview downloaded to: $DL_PATH"
-          find "$DL_PATH"
-
-      ### Run the installer and check that the installation looks OK
-
-      - name: Run installer (Windows)
-        if: ${{ startsWith(matrix.os, 'windows') }}
-        # The installer spawns a new process and exits immediately, meaning
-        # that the shell thinks it has finishes, tries to exit to move onto
-        # the next step in the job, and kills the child process that is
-        # trying to do the installation.
-        # Wrapping the installer in "Start-Process ... -Wait" means that
-        # this step doesn't exit until the installer has finished.
-        shell: powershell
-        run: |
-          Start-Process -FilePath "${{ env.DL_WIN_PATH }}/setupSasView.exe" -ArgumentList "/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /ALLUSERS /SKIPLICENSE=true /LANG=english /NOICONS /TASKS='' /LOG=${{ env.DL_WIN_PATH }}/install.log /DIR=${{ env.INSTALL_WIN_PATH }}" -Wait
-
-      - name: Check installation log (Windows)
-        if: ${{ startsWith(matrix.os, 'windows') }}
-        run: |
-          echo "Contents of installation log '$DL_PATH/install.log':"
-          cat $DL_PATH/install.log
-
-      - name: Run installer (Linux)
-        if: ${{ startsWith(matrix.os, 'ubuntu') }}
-        run: |
-          # $INSTALL_PATH is already the base directory
-          tar xf "$DL_PATH/SasView6.tar.gz"
-
-      - name: Check installation files
-        if: ${{ !startsWith(matrix.os, 'macos') }}
-        run: |
-          echo "File listing of SasView installed in '$INSTALL_PATH'"
-          find "$INSTALL_PATH"
-
-      - name: Try running the installation (Windows)
-        if: ${{ startsWith(matrix.os, 'windows') }}
-        # If sasview has crashed on its own, then this should return an error
-        run: |
-          $RUN_SASVIEW &
-          sleep 60s
-          kill %1
-
-      - name: Install X11 libraries (Linux)
-        if: ${{ startsWith(matrix.os, 'ubuntu') }}
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          sudo apt-get -y install libegl1 libopengl0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils xvfb libxcb-cursor0
-
-      - name: Try running the installation (Linux)
-        if: ${{ startsWith(matrix.os, 'ubuntu' )}}
-        # If sasview has crashed on its own, then this should return an error
-        run: |
-          (
-            echo "## START SASVIEW"
-            xvfb-run -a --server-args="-screen 0 1024x768x24" $RUN_SASVIEW 2>&1 |
-            tee sasview-test.log
-          ) &
-          svpid=$!
-          (
-            set -e
-            sleep 20s
-            echo "## PULSE CHECK"
-            kill -0 $svpid
-            echo "## PULSE OK"
-            sleep 40s
-            echo "## FINISHING SMOKE TEST"
-            kill $svpid
-            echo "## SMOKE TEST COMPLETE"
-            exit 0
-          ) &
-          pulsepid=$1
-          wait $pulsepid
-          # Check the log file for successful startup
-          grep "SasView session started" sasview-test.log
-
-      - name: Try running the installation (macOS)
-        if: ${{ startsWith(matrix.os, 'macOS' )}}
-        run: |
-          hdiutil attach $DL_PATH/SasView6-${{ matrix.os }}.dmg
-          # Testing scripting interface by running simple model generation through sasmodels compare
-          /Volumes/SasView6/SasView6.app/Contents/MacOS/sasview -m sasmodels.compare cylinder -noplot
-
-      ### Optionally attempt to work with the debug tarball from pyinstaller
-
-      - name: Retrieve installer debug tarball
-        if: ${{ env.INSTALLER_USE_DEBUG == 'true' }}
-        id: download-old-debug
-        uses: dawidd6/action-download-artifact@v6
-        with:
-          # Select a specific installer image based on the GitHub Actions run id
-          run_id: ${{ env.INSTALLER_OLD_RUNID }}
-          name: Debug-SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
-          path: downloads
-          if_no_artifact_found: fail
-
-      - name: Extract debug tarball
-        if: ${{ env.INSTALLER_USE_DEBUG == 'true' }}
-        run: |
-          mkdir unpack
-          cd unpack
-          tar zxf ../downloads/sasview-pyinstaller-dist.tar.gz
-
-      - name: Check debug installation files
-        if: ${{ env.INSTALLER_USE_DEBUG == 'true' && startsWith(matrix.os, 'windows') }}
-        run: |
-          echo "File listing of SasView install bundle unpacked in 'unpack'"
-          find unpack
-
-      - name: Try running debug unpack
-        if: ${{ env.INSTALLER_USE_DEBUG == 'true' && startsWith(matrix.os, 'windows') }}
-        run: |
-          cd unpack/sasview
-          ./sasview.exe
+      # - name: Publish installer package
+      #   if: ${{ matrix.installer }}
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
+      #     path: |
+      #       installers/dist/setupSasView*.exe
+      #       installers/dist/SasView6-macos-13.dmg
+      #       installers/dist/SasView6-macos-latest.dmg
+      #       installers/dist/SasView*.tar.gz
+      #     if-no-files-found: ignore
+  #
+  #
+  # test-installer:
+  #   needs: [ build-matrix ]
+  #
+  #   strategy:
+  #     matrix:
+  #       os: [ windows-latest, macos-latest, ubuntu-22.04 ]
+  #       python-version: [ 3.11 ]
+  #     fail-fast: false
+  #
+  #   name: Test installer
+  #
+  #   runs-on: ${{ matrix.os }}
+  #
+  #   steps:
+  #     - name: Set variables (Windows)
+  #       if: ${{ startsWith(matrix.os, 'windows') }}
+  #       run: |
+  #         echo "INSTALL_PATH=$PWD/sasview/" >> $GITHUB_ENV
+  #         echo "RUN_SASVIEW=$PWD/sasview/sasview.exe" >> $GITHUB_ENV
+  #
+  #     - name: Set variables (Linux)
+  #       if: ${{ startsWith(matrix.os, 'ubuntu') }}
+  #       run: |
+  #         echo "INSTALL_PATH=$PWD/sasview/" >> $GITHUB_ENV
+  #         echo "RUN_SASVIEW=$PWD/sasview/sasview" >> $GITHUB_ENV
+  #
+  #     - name: Set variables (Windows Powershell)
+  #       if: ${{ startsWith(matrix.os, 'windows') }}
+  #       shell: powershell
+  #       # unfortunately we end up tripping over ourselves with paths
+  #       # later on and need a PS version of the install path
+  #       run: |
+  #         "INSTALL_WIN_PATH=$(Get-Location)/sasview/" >> $env:GITHUB_ENV
+  #
+  #     ### Obtain the installer, either from the previous step
+  #     ### or from a previous run of the workflow
+  #
+  #     - name: Retrieve installer (workflow image)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' }}
+  #       uses: actions/download-artifact@v4
+  #       id: download
+  #       with:
+  #         name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
+  #
+  #     - name: Set variables for download (workflow image)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' }}
+  #       run: |
+  #         echo "DL_PATH=${{steps.download.outputs.download-path}}" >> $GITHUB_ENV
+  #
+  #     - name: Set variables for download (workflow image) (Windows)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE != 'true' && startsWith(matrix.os, 'windows') }}
+  #       shell: powershell
+  #       run: |
+  #         "DL_WIN_PATH=${{steps.download.outputs.download-path}}" >> $env:GITHUB_ENV
+  #
+  #     - name: Retrieve installer (old image)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' }}
+  #       id: download-old-installer
+  #       uses: dawidd6/action-download-artifact@v6
+  #       with:
+  #         # Select a specific installer image based on the GitHub Actions run id
+  #         run_id: ${{ env.INSTALLER_OLD_RUNID }}
+  #         name: SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
+  #         path: downloads
+  #         if_no_artifact_found: fail
+  #
+  #     - name: Set variables for download (old image)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' }}
+  #       run: |
+  #         echo "DL_PATH=$PWD/downloads" >> $GITHUB_ENV
+  #
+  #     - name: Set variables for download (old image) (Windows)
+  #       if: ${{ env.INSTALLER_USE_OLD_IMAGE == 'true' && startsWith(matrix.os, 'windows') }}
+  #       shell: powershell
+  #       run: |
+  #         "DL_WIN_PATH=$(Get-Location)/downloads" >> $env:GITHUB_ENV
+  #
+  #     - name: Check downloads
+  #       run: |
+  #         echo "Sasview downloaded to: $DL_PATH"
+  #         find "$DL_PATH"
+  #
+  #     ### Run the installer and check that the installation looks OK
+  #
+  #     - name: Run installer (Windows)
+  #       if: ${{ startsWith(matrix.os, 'windows') }}
+  #       # The installer spawns a new process and exits immediately, meaning
+  #       # that the shell thinks it has finishes, tries to exit to move onto
+  #       # the next step in the job, and kills the child process that is
+  #       # trying to do the installation.
+  #       # Wrapping the installer in "Start-Process ... -Wait" means that
+  #       # this step doesn't exit until the installer has finished.
+  #       shell: powershell
+  #       run: |
+  #         Start-Process -FilePath "${{ env.DL_WIN_PATH }}/setupSasView.exe" -ArgumentList "/SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /ALLUSERS /SKIPLICENSE=true /LANG=english /NOICONS /TASKS='' /LOG=${{ env.DL_WIN_PATH }}/install.log /DIR=${{ env.INSTALL_WIN_PATH }}" -Wait
+  #
+  #     - name: Check installation log (Windows)
+  #       if: ${{ startsWith(matrix.os, 'windows') }}
+  #       run: |
+  #         echo "Contents of installation log '$DL_PATH/install.log':"
+  #         cat $DL_PATH/install.log
+  #
+  #     - name: Run installer (Linux)
+  #       if: ${{ startsWith(matrix.os, 'ubuntu') }}
+  #       run: |
+  #         # $INSTALL_PATH is already the base directory
+  #         tar xf "$DL_PATH/SasView6.tar.gz"
+  #
+  #     - name: Check installation files
+  #       if: ${{ !startsWith(matrix.os, 'macos') }}
+  #       run: |
+  #         echo "File listing of SasView installed in '$INSTALL_PATH'"
+  #         find "$INSTALL_PATH"
+  #
+  #     - name: Try running the installation (Windows)
+  #       if: ${{ startsWith(matrix.os, 'windows') }}
+  #       # If sasview has crashed on its own, then this should return an error
+  #       run: |
+  #         $RUN_SASVIEW &
+  #         sleep 60s
+  #         kill %1
+  #
+  #     - name: Install X11 libraries (Linux)
+  #       if: ${{ startsWith(matrix.os, 'ubuntu') }}
+  #       env:
+  #         DEBIAN_FRONTEND: noninteractive
+  #       run: |
+  #         sudo apt-get -y install libegl1 libopengl0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils xvfb libxcb-cursor0
+  #
+  #     - name: Try running the installation (Linux)
+  #       if: ${{ startsWith(matrix.os, 'ubuntu' )}}
+  #       # If sasview has crashed on its own, then this should return an error
+  #       run: |
+  #         (
+  #           echo "## START SASVIEW"
+  #           xvfb-run -a --server-args="-screen 0 1024x768x24" $RUN_SASVIEW 2>&1 |
+  #           tee sasview-test.log
+  #         ) &
+  #         svpid=$!
+  #         (
+  #           set -e
+  #           sleep 20s
+  #           echo "## PULSE CHECK"
+  #           kill -0 $svpid
+  #           echo "## PULSE OK"
+  #           sleep 40s
+  #           echo "## FINISHING SMOKE TEST"
+  #           kill $svpid
+  #           echo "## SMOKE TEST COMPLETE"
+  #           exit 0
+  #         ) &
+  #         pulsepid=$1
+  #         wait $pulsepid
+  #         # Check the log file for successful startup
+  #         grep "SasView session started" sasview-test.log
+  #
+  #     - name: Try running the installation (macOS)
+  #       if: ${{ startsWith(matrix.os, 'macOS' )}}
+  #       run: |
+  #         hdiutil attach $DL_PATH/SasView6-${{ matrix.os }}.dmg
+  #         # Testing scripting interface by running simple model generation through sasmodels compare
+  #         /Volumes/SasView6/SasView6.app/Contents/MacOS/sasview -m sasmodels.compare cylinder -noplot
+  #
+  #     ### Optionally attempt to work with the debug tarball from pyinstaller
+  #
+  #     - name: Retrieve installer debug tarball
+  #       if: ${{ env.INSTALLER_USE_DEBUG == 'true' }}
+  #       id: download-old-debug
+  #       uses: dawidd6/action-download-artifact@v6
+  #       with:
+  #         # Select a specific installer image based on the GitHub Actions run id
+  #         run_id: ${{ env.INSTALLER_OLD_RUNID }}
+  #         name: Debug-SasView-Installer-${{ matrix.os }}-${{ matrix.python-version }}
+  #         path: downloads
+  #         if_no_artifact_found: fail
+  #
+  #     - name: Extract debug tarball
+  #       if: ${{ env.INSTALLER_USE_DEBUG == 'true' }}
+  #       run: |
+  #         mkdir unpack
+  #         cd unpack
+  #         tar zxf ../downloads/sasview-pyinstaller-dist.tar.gz
+  #
+  #     - name: Check debug installation files
+  #       if: ${{ env.INSTALLER_USE_DEBUG == 'true' && startsWith(matrix.os, 'windows') }}
+  #       run: |
+  #         echo "File listing of SasView install bundle unpacked in 'unpack'"
+  #         find unpack
+  #
+  #     - name: Try running debug unpack
+  #       if: ${{ env.INSTALLER_USE_DEBUG == 'true' && startsWith(matrix.os, 'windows') }}
+  #       run: |
+  #         cd unpack/sasview
+  #         ./sasview.exe
